{
 "title": "Jellyfin Activity Dashboard",
 "description": "Works with the jellyfin user activity exporter to display what users have watched and the popularity of content.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "user",
    "query": {
     "query": "label_values(jellyfin_playback_progress_percent,username)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Unique Users",
   "type": "stat",
   "description": "The number of unique users who watched a session in the past 24 hours.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by(username) (jellyfin_playback_progress_percent{job=\"jellyfin\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Jellyfin Sessions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jellyfin_active_sessions_total{job=\"jellyfin\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top shows",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "count(\r\n  sum by (series, username) (\r\n    count_over_time(jellyfin_playback_progress_percent{job=\"jellyfin\", is_paused=\"false\", series!~\"^$\"}[$__range])\r\n  ) > 0\r\n) by (series)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top movies",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "count(\r\n  sum by (now_playing, username) (\r\n    count_over_time(jellyfin_playback_progress_percent{job=\"jellyfin\", is_paused=\"false\", series=~\"^$\"}[$__range])\r\n  ) > 0\r\n) by (now_playing)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "${user}",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "repeat": "user",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (username, now_playing, series) (\r\n  jellyfin_playback_progress_percent{job=\"jellyfin\", username=\"$user\", is_paused=\"false\"}\r\n)",
     "legendFormat": "{{series}} - {{now_playing}} "
    }
   ]
  }
 ]
}